name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: heyinc/setup-ruby-with-takumi-guard@v1
        with:
          working-directory: .
          bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
          ruby-version: '3.4'
      - name: Run RuboCop
        run: bundle exec rubocop
